### PR TITLE
add select-example

### PR DESCRIPTION
**Pull request by sonokougg**
@cdra0624

---
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/react-tutorials/1)

### CODE REVIEW

**Comment by zigen** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pages/select-example.js, line 30 at r1](https://reviewable.io/reviews/tigerscave/react-tutorials/1#-LE33vKc2nmwglBzXI0E:-LE33vKc2nmwglBzXI0F:bvyvab0) ([raw file](https://github.com/tigerscave/react-tutorials/blob/5e9e498c9cc54d9aba27eaef429096db9edc39a5/pages/select-example.js#L30)):*
> ```JavaScript
>     this.handleSelectChange = e => {
>       console.log(e.target.value);
>       if(e.target.value=="Adaniya"){
> ```

why did you use if-else statement?
there are a lot of similar pattern...
now it works, but you can write much better code!

---


*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/react-tutorials/1)*

**Comment by azamiya** [comment]
apart from? instead of ?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/react-tutorials/1#-:-LE3TvMI8z_Gd8PdmNgK:be0fp8a)*

**Comment by azamiya** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pages/select-example.js, line 30 at r1](https://reviewable.io/reviews/tigerscave/react-tutorials/1#-LE33vKc2nmwglBzXI0E:-LE3UI920iC_UVamxmzj:b1e1l72) ([raw file](https://github.com/tigerscave/react-tutorials/blob/5e9e498c9cc54d9aba27eaef429096db9edc39a5/pages/select-example.js#L30)):*
<details><summary><i>Previously, zigen (zigen) wrote…</i></summary><blockquote>

why did you use if-else statement?
there are a lot of similar pattern...
now it works, but you can write much better code!
</blockquote></details>

chooseName ? is this name?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/react-tutorials/1)*

**Comment by zigen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pages/select-example.js, line 36 at r4](https://reviewable.io/reviews/tigerscave/react-tutorials/1#-LE4YoSv84dehoDlq_9S:-LE4YoSv84dehoDlq_9T:b-adme5f) ([raw file](https://github.com/tigerscave/react-tutorials/blob/5318a43ee11abee46d725737f00fb80eb646f5c6/pages/select-example.js#L36)):*
> ```JavaScript
>       }
> 
>       const selectedName = data.filter(d => checkName(d))[0]
> ```

remove arrow. this makes function.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/react-tutorials/1)*

**Comment by zigen** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/react-tutorials/1#-:-LE8nPI729WTKOF9ebDl:bnfp4nl)*

**Pull request closed without merging**
